DOMAIN = "min_renovasjon"
CONF_STREET_NAME = "street_name"
CONF_STREET_CODE = "street_code"
CONF_HOUSE_NO = "house_no"
CONF_COUNTY_ID = "county_id"
CONF_DATE_FORMAT = "date_format"
DEFAULT_DATE_FORMAT = "%d/%m/%Y"
CONST_KOMMUNE_NUMMER = "Kommunenr"
CONST_APP_KEY = "RenovasjonAppKey"
CONST_URL_FRAKSJONER = "https://komteksky.norkart.no/komtek.renovasjonwebapi/api/fraksjoner"
CONST_URL_TOMMEKALENDER = "https://komteksky.norkart.no/komtek.renovasjonwebapi/api/tommekalender?gatenavn=[gatenavn]&gatekode=[gatekode]&husnr=[husnr]"
CONST_APP_KEY_VALUE = "AE13DEEC-804F-4615-A74E-B4FAC11F0A30"
CONF_FRACTION_IDS = "fraction_ids"
CONF_FRACTION_ID = "fraction_id"
ADDRESS_LOOKUP_URL = "https://ws.geonorge.no/adresser/v1/sok?"
APP_CUSTOMERS_URL = "https://www.webatlas.no/wacloud/servicerepository/CatalogueService.svc/json/GetRegisteredAppCustomers"
KOMTEK_API_BASE_URL = "https://norkartrenovasjon.azurewebsites.net/proxyserver.ashx"

